### ISSUE TITLE
Have a proper versioning system

### ISSUE THREAD

**Issue by arihant2math** [wfxr/forgit#233]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [x] Mac OS X
    - [x] Windows
    - [x] Others:
- Shell
    - [x] bash
    - [x] zsh
    - [x] fish

## Problem / Steps to reproduce
forgit is not versioned. This is a problem because brew (see #194) depends on forgit being versioned.

**Comment by carlfriedrich** [comment]
I'd like to get this rolling. IMO the only thing to do is start creating tags.

Some questions to discuss @wfxr @cjappl:

1. Is it okay for you if I do this? I am volunteering to maintain the release process, so no work on your side, if you are fine with that. @wfxr If you as the initial creator of forgit want to maintain releases, though, I would be totally fine with that as well.

2. Do you have an opinion on whether to use [semantic versioning](https://semver.org/) or [calendar versioning](https://calver.org/)? Or do you have another preferred versioning scheme? IMO semantic versioning (major.minor.fix) seems legit for this project. We probably wouldn't ever use the fix revision, though.

3. Should we define a version for the current master already? If you prefer semantic versioning as well, do you think [we are on 1.0.0 already](https://semver.org/#how-do-i-know-when-to-release-100)? Since forgit is out there in the public and used by lots of people, and we try to keep changes backwards-compatible all the time, I would say yes. So we could define a 1.0.0 version. @wfxr Maybe there is a former version of forgit which you would think of as the first stable version? Or we could just tag the current master with 1.0.0?

Let me know what you think.

**Comment by wfxr** [comment]
@carlfriedrich

1. Totally fine. And I appreciate all your work for `forgit`.

2. I think [calendar versioning](https://calver.org/) is more appreciate for a project like `forgit`. We can release new versions periodically without having to think too much about how to define a new version tag or when to do a release. The release processes may be fully automated through the github workflow.

3. This seems not be a problem if we choose [calendar versioning](https://calver.org/)?

**Comment by cjappl** [comment]
All of the above WFM! 🚀

**Comment by carlfriedrich** [comment]
@wfxr 

>     1. Totally fine. And I appreciate all your work for `forgit`.

Great, thank you!

>     2. I think [calendar versioning](https://calver.org/) is more appreciate for a project like `forgit`. We can release new versions periodically without having to think too much about how to define a new version tag or when to do a release. The release processes may be fully automated through the github workflow.

Release automating via GitHub workflow is what I thought of as well, that's definitely a good idea. So do you think we should do monthly releases then? This would mean if anybody pushes a feature on the beginning of a month, we would have to wait until the end of the month for a release.

I personally wouldn't mind creating tags manually everytime we merge something, always increasing the minor number by 1, so that we can release new features quickly. WDYT?

**Comment by carlfriedrich** [comment]
@wfxr That sounds useful. I would propose tagging the current master with 22.11.0 as the initial release then, and I will come up with a GitHub action for automatic monthly releases within the next two weeks.

I see two separate actions here:

1. Tag creation (triggered on every 1st day of the month)
    - Create a release tag

2. Release creation (triggered on new tags)
    - Create a GitHub release
    - Generate a changelog

Anything to add?
