### ISSUE TITLE
[feature request] forgitgcm   git commit message

### ISSUE THREAD

**Issue by cocoonkid** [wfxr/forgit#276]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [x] Mac OS X

- Shell

    - [x] zsh

[Feature request]  forgitgcm   git commit message

it would be amazing to use alias `gcm ` to enable the user to choose from all commit messages to quickly find a similar one, edit it and apply.

Commit messages often repeat or rhyme.

Thanks for consideration.

**Comment by carlfriedrich** [comment]
Hi @cocoonkid, thanks for your suggestion.

This would require forgit to save a list of all commit messages, which would be something completely new to the project. For me this seems out of scope. At least I myself wouldn't need this (what kind of projects do you work on so that you have many similar messages?).

@cjappl @wfxr What do you say? Are we open for PRs on this or is this something `forgit` shouldn't be reponsible for?

**Comment by cjappl** [comment]
Yeah this seems a little out of the scope for me. I would be ok closing this issue.

**Comment by cocoonkid** [comment]
Understood!  Thanks for taking the time!
