### ISSUE TITLE
AUR Auto Update Action Failed

### ISSUE THREAD

**Issue by cjappl** [wfxr/forgit#357]
https://github.com/wfxr/forgit/actions/runs/8104493574

Not sure what happened, filing it here so we can look into it

**Comment by sandr01d** [comment]
Thanks for letting me know. The issue here was that completions/git-forgit.zsh has been removed from this repo, but I hadn't removed the corresponding line from the installation script in the AUR to not break the package. The action we use to publish the AUR package runs a test build, which failed because of the missing file. Now with the removal of completions/git-forgit.zsh in the release, I've updated the AUR package accordingly and released the latest version there. Should be all fine now.
