### ISSUE TITLE
`gbl` should have nice syntax coloring (or optionally use GIT_PAGER or `bat`?)

### ISSUE THREAD

**Issue by cjappl** [wfxr/forgit#370]
Currently if you use `gbl` you get a rather dull monochrome blame:

<img width="1424" alt="Screenshot 2024-03-18 at 2 52 36 PM" src="https://github.com/wfxr/forgit/assets/14171107/704dc44e-f778-49f2-873a-909acf50b000">

It would be nice if we could put this through a nicer pager, or add syntax highlighting somehow.

**Comment by sandr01d** [comment]
I gave this a shot using bat's syntax highlighting. Getting bat to apply syntax highlighting is easy. Bat determines which highlighting to use based on the file name and there is a `--file-name` option that can be used when reading from stdin. However the results heavily depend on the language.

For some languages this works nicely:

![image](https://github.com/wfxr/forgit/assets/88739791/26d1150f-b16c-4307-a5c7-e99bd3013cfb)

Some syntaxes, such as yaml, simply color the whole line, which results in the git annotation being colored as well

![image](https://github.com/wfxr/forgit/assets/88739791/91de648c-ef0a-4685-bcc3-e39e3efac257)

I find this problematic, especially when using `--color-by-age` or `--color-lines` where git colors annotations to highlight them. When not using syntax highlighting they clearly stand out. With syntax highlighting not so much:

![image](https://github.com/wfxr/forgit/assets/88739791/2a39fcb7-cf60-4352-af94-0a531159f883)

In the above picture, the green annotations are highlighted with `--color-lines` everything else is bats syntax highlighting.
A similar issue exists with multi line strings in bash or multi line code snippets in markdown, where bat obviously can't tell that the annotation is not part of the string:

![image](https://github.com/wfxr/forgit/assets/88739791/5ca594f5-74c0-4b17-b962-871fedb15eb4)

I think doing syntax highlighting this way will always be hit and miss.
Delta [supports coloring git blame output](https://dandavison.github.io/delta/git-blame.html) - unfortunately it does not seem to have a way to determine the language when reading from stding (see https://github.com/dandavison/delta/issues/1231). The black and gray background coloring is already achievable by setting delta as your pager.

![image](https://github.com/wfxr/forgit/assets/88739791/c3eccb1b-c865-4a0f-84c8-f3b946574e67)

**Comment by ccoVeille** [comment]
isn't it already possible ?

FORGIT_BLAME_PAGER='bat --color=always -l log' git forgit blame

![image](https://github.com/wfxr/forgit/assets/3875889/6a20d4c2-cb88-408a-ae02-95a8c174a3d8)

FORGIT_BLAME_PAGER='bat --color=always -l gitlog' git forgit blame

![image](https://github.com/wfxr/forgit/assets/3875889/d426eb40-2732-4ef3-830d-46f460839723)

**Comment by sandr01d** [comment]
> isn't it already possible ?
>
> FORGIT_BLAME_PAGER='bat --color=always -l log' git forgit blame

@ccoVeille this would color everything using the same syntax (log), but ideally we would have syntax highlighting based on the file.

`bat` (which we already use for `gbl`) supports syntax highlighting based on the file extension. We currently do not pass the file name to `bat` and only pipe the content of the file when using `gbl`. We could use the `--file-name` parameter to make `bat` use the correct syntax. I did a quick and dirty implementation to see what the results would look like. Some files look fine, e.g.

![image](https://github.com/wfxr/forgit/assets/88739791/6db7c95f-249d-46ba-8616-56e0c996f3bc)

For others, the annotations get colored, since `bat` isn't aware of them.

![image](https://github.com/wfxr/forgit/assets/88739791/98d57b1b-6b14-4150-b80f-34195d06db6f)

This is especially bad when using `--color-by-age` or `--color-lines` since it makes the highlights in the annotations less visible IMO:

![image](https://github.com/wfxr/forgit/assets/88739791/26ea7fd4-19c6-4fab-abd8-bf05b2ccbf2b)

Would be interested what others think, but I personally would value visible highlights from `--color-lines` more than syntax highlighting in the context of `git blame`.
delta has special [highlighting for git blame](https://dandavison.github.io/delta/git-blame.html). This can already be used when configuring delta as pager.

**Comment by ccoVeille** [comment]
Thanks for your reply. It's clearer.

I like the implementation you made

**Comment by carlfriedrich** [comment]
@sandr01d I would also value the `--color-lines` more than syntax highlighting of the file.

However, if delta supports git blame highlighting (which is cool, wasn't aware of that!), then we have a solution, don't we? We could add delta as a soft dependency, just like we do with `bat`. How about that?

Personally, I am using [`diff-so-fancy`](https://github.com/so-fancy/diff-so-fancy) as a pager because I like its diff presentation more than delta's. That's personal preference, though, and I would actually like using `delta` for `gbl` if it does something useful there.

**Comment by sandr01d** [comment]
I agree with you @carlfriedrich. The AUR package already has `delta` as an optional dependency and we also list it on our README. The only thing to look out for with `delta` and blame is https://github.com/dandavison/delta/issues/1278.

**Comment by ccoVeille** [comment]
@carlfriedrich it's indeed a good solution.

Also, you could mention delta as a recommended dependency. And the code react to `delta` availability.

But it might be what you were thinking about

**Comment by sandr01d** [comment]
> Also, you could mention delta as a recommended dependency

We already mention it as an optional dependency on the README [here](https://github.com/wfxr/forgit?tab=readme-ov-file#-optional-dependencies) and it's set as an optional dependency in the AUR package as well.

> And the code react to delta availability.

We automatically use delta when it's set as the respective pager in the git config. I don't see the need to add extra code here, since this can easily be configured. Let me know if any of you have a different opinion on this, otherwise I'm going to close this issue sometime soon.
