### ISSUE TITLE
Fuzzy search not working

### ISSUE THREAD

**Issue by dansdantas** [wfxr/forgit#4]
I don't know if it is intentional or not, but can not use fuzzy search on any window created by forgit.  Only matching exactly file name works bringing correct results.

Thanks for your work. I've been using for some weeks and it is really helping my workflow.

**Comment by wfxr** [comment]
Yes, `-e` flag which enable "exact-match" has been given when calling fzf inner forgit.
I plan to add an environment variable like `FORGIT_FZF_DEFAULT_OPTS` by which user can give custom options to fzf used in forgit.
Before it been done, you can add a leading `'` character on the query term to use "fuzzy-match" instead of "exact-match".

**Comment by wfxr** [comment]
Done. 
Personal prefer options has been moved to `FORGIT_FZF_DEFAULT_OPTS`. You can also add custom fzf options here.

**Comment by dansdantas** [comment]
Thank you.
