### ISSUE TITLE
alias method

### ISSUE THREAD

**Issue by adberard** [wfxr/forgit#43]
The way to set up alias is seem very unconventional, is there a reason to not use the alias command instead ?
```
forgit_log=glo
forgit_diff=gd
forgit_add=ga
forgit_reset_head=grh
forgit_ignore=gi
forgit_restore=gcf
forgit_clean=gclean
forgit_stash_show=gss

```

```
alias glo='forgit::log'
alias gd='forgit::diff'
alias ga='forgit::add'
alias grh='forgit::reset_head'
alias gi='forgit::ignore'
alias gcf='forgit::restore'
alias gclean='forgit::clean'
alias gss='forgit::stash_show'
```

**Comment by wfxr** [comment]
Because the first way works and it is no more complicated than the second way. It also gives us the freedom to modify the implementation while keep compatibility (eg. someday we want to add support for `sh` but `sh` doesn't allow `::` existed in the function name).

Of course, I don't mean that the first way is perfect and the second way is nothing. Both way have their own advantages and disadvantages, and in most cases can work well. Just in my opinion, the first way is slight better, nothing more.
