### ISSUE TITLE
Add a git status support that allows to stash/unstash files

### ISSUE THREAD

**Issue by 3v1n0** [wfxr/forgit#98]
## Check list

- [x] I have read through the [README](https://github.com/wfxr/forgit/blob/master/README.md)
- [x] I have the latest version of forgit
- [x] I have searched through the existing issues

## Environment info

- OS
    - [x] Linux
    - [ ] Mac OS X
    - [ ] Windows
    - [ ] Others:
- Shell
    - [ ] bash
    - [x] zsh
    - [ ] fish

## Problem / Steps to reproduce

Would be nice to have a `git status` view similar to the [https://github.com/timbrel/GitSavvy](GitSavvy) one ([see screenshot](https://cloud.githubusercontent.com/assets/5016978/6704171/2f236466-cd02-11e4-9b7d-22cc880b5e9d.png)) that allows to quickly stash/unstash files and see the current status easily.

**Comment by cjappl** [comment]
@wfxr would you like to respond or close this as you see appropriate?

**Comment by wfxr** [comment]
I have read this issue, but I feel that the value this feature brings is not as much as the complexity it will require.Although it may be possible, implementing a status layout like the screenshot showed is not a good use of fzf.

Since forgit is positioned as a lightweight plugin aimed to enchance file selecting and previewing related operations for git, using fuzzy finder fzf. I want to keep the functions simple, brief, no learning cost(almost), easy to maintain and also easy to expand by users themself. If one look for a powerful gui/tui tool for git, tools like [tpope/vim-fugitive](https://github.com/tpope/vim-fugitive) and [jesseduffield/lazygit](https://github.com/jesseduffield/lazygit) etc already do it well.
